package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_1.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectTemplates()
    templates = arrayListOf(RelativeId("Template1"))

    vcs {
        remove(DslContext.settingsRoot.id!!)
    }

    expectSteps {
        maven {
            goals = "clean test"
            mavenVersion = defaultProvidedVersion()
        }
    }
    steps {
        items.removeAt(0)
    }

    triggers {
        remove {
            vcs {
                id = "TRIGGER_1"
            }
        }
    }
}
