package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_4"
                param("clientId", "9e046f77aacc4115726a")
                param("defaultTokenScope", "public_repo,repo,repo:status,write:repo_hook")
                param("secure:clientSecret", "credentialsJSON:a86d6830-5b13-449f-89a7-4a958552c76f")
                param("displayName", "GitHub.com")
                param("gitHubUrl", "https://github.com/")
                param("providerType", "GitHub")
            }
        }
    }
}
