package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Template
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'Template1'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Template({
    id("Template1")
    name = "Template1"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        script {
            name = "Prepare environment"
            id = "RUNNER_1"
            scriptContent = "<do something>"
        }
        script {
            name = "Perform cleanup"
            id = "RUNNER_4"
            scriptContent = "<do something>"
        }
    }

    triggers {
        vcs {
            id = "TRIGGER_1"
        }
    }
}))

